

/* who said C doesn't have namespaces? */
#  define VkInstance glfw__VkInstance
#  define VkResult glfw__VkResult
#  define VkPhysicalDevice glfw__VkPhysicalDevice
#  define VK_SUCCESS GLFW__VK_SUCCESS
#  define VK_NOT_READY GLFW__VK_NOT_READY
#  define VK_TIMEOUT GLFW__VK_TIMEOUT
#  define VK_EVENT_SET GLFW__VK_EVENT_SET
#  define VK_EVENT_RESET GLFW__VK_EVENT_RESET
#  define VK_INCOMPLETE GLFW__VK_INCOMPLETE
#  define VK_ERROR_OUT_OF_HOST_MEMORY GLFW__VK_ERROR_OUT_OF_HOST_MEMORY
#  define VK_ERROR_OUT_OF_DEVICE_MEMORY GLFW__VK_ERROR_OUT_OF_DEVICE_MEMORY
#  define VK_ERROR_INITIALIZATION_FAILED GLFW__VK_ERROR_INITIALIZATION_FAILED
#  define VK_ERROR_DEVICE_LOST GLFW__VK_ERROR_DEVICE_LOST
#  define VK_ERROR_MEMORY_MAP_FAILED GLFW__VK_ERROR_MEMORY_MAP_FAILED
#  define VK_ERROR_LAYER_NOT_PRESENT GLFW__VK_ERROR_LAYER_NOT_PRESENT
#  define VK_ERROR_EXTENSION_NOT_PRESENT GLFW__VK_ERROR_EXTENSION_NOT_PRESENT
#  define VK_ERROR_FEATURE_NOT_PRESENT GLFW__VK_ERROR_FEATURE_NOT_PRESENT
#  define VK_ERROR_INCOMPATIBLE_DRIVER GLFW__VK_ERROR_INCOMPATIBLE_DRIVER
#  define VK_ERROR_TOO_MANY_OBJECTS GLFW__VK_ERROR_TOO_MANY_OBJECTS
#  define VK_ERROR_FORMAT_NOT_SUPPORTED GLFW__VK_ERROR_FORMAT_NOT_SUPPORTED
#  define VK_ERROR_SURFACE_LOST_KHR GLFW__VK_ERROR_SURFACE_LOST_KHR
#  define VK_ERROR_NATIVE_WINDOW_IN_USE_KHR GLFW__VK_ERROR_NATIVE_WINDOW_IN_USE_KHR
#  define VK_SUBOPTIMAL_KHR GLFW__VK_SUBOPTIMAL_KHR
#  define VK_ERROR_OUT_OF_DATE_KHR GLFW__VK_ERROR_OUT_OF_DATE_KHR
#  define VK_ERROR_INCOMPATIBLE_DISPLAY_KHR GLFW__VK_ERROR_INCOMPATIBLE_DISPLAY_KHR
#  define VK_ERROR_VALIDATION_FAILED_EXT GLFW__VK_ERROR_VALIDATION_FAILED_EXT
#  define VK_RESULT_MAX_ENUM GLFW__VK_RESULT_MAX_ENUM
#  define VkStructureType glfw__VkStructureType
#  define VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR GLFW__VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR
#  define VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR GLFW__VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR
#  define VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR GLFW__VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR
#  define VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR GLFW__VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR
#  define VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK GLFW__VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK
#  define VK_STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT GLFW__VK_STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT
#  define VK_STRUCTURE_TYPE_HEADLESS_SURFACE_CREATE_INFO_EXT GLFW__VK_STRUCTURE_TYPE_HEADLESS_SURFACE_CREATE_INFO_EXT
#  define VK_STRUCTURE_TYPE_HEADLESS_SURFACE_CREATE_INFO_EXT GLFW__VK_STRUCTURE_TYPE_HEADLESS_SURFACE_CREATE_INFO_EXT
#  define VK_STRUCTURE_TYPE_MAX_ENUM GLFW__VK_STRUCTURE_TYPE_MAX_ENUM
#  define VkExtensionProperties glfw__VkExtensionProperties
#  define PFN_vkGetInstanceProcAddr glfw__PFN_vkGetInstanceProcAddr
#  define VkSurfaceKHR glfw__VkSurfaceKHR
#  define VkHeadlessSurfaceCreateInfoEXT glfw__VkHeadlessSurfaceCreateInfoEXT
#  define PFN_vkCreateHeadlessSurfaceEXT glfw__PFN_vkCreateHeadlessSurfaceEXT
#  define PFN_vkEnumerateInstanceExtensionProperties glfw__PFN_vkEnumerateInstanceExtensionProperties

#include "deps/glfw/UnityBuild.c"

#  undef vkGetInstanceProcAddr
#  undef PFN_vkEnumerateInstanceExtensionProperties
#  undef VkExtensionProperties
#  undef PFN_vkGetInstanceProcAddr
#  undef VkSurfaceKHR
#  undef VkHeadlessSurfaceCreateInfoEXT
#  undef PFN_vkCreateHeadlessSurfaceEXT
#  undef VK_ERROR_SURFACE_LOST_KHR
#  undef VK_ERROR_NATIVE_WINDOW_IN_USE_KHR
#  undef VK_SUBOPTIMAL_KHR
#  undef VK_ERROR_OUT_OF_DATE_KHR
#  undef VK_ERROR_INCOMPATIBLE_DISPLAY_KHR
#  undef VK_ERROR_VALIDATION_FAILED_EXT
#  undef VK_RESULT_MAX_ENUM
#  undef VkStructureType
#  undef VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR
#  undef VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR
#  undef VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR
#  undef VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR
#  undef VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK
#  undef VK_STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT
#  undef VK_STRUCTURE_TYPE_HEADLESS_SURFACE_CREATE_INFO_EXT
#  undef VK_STRUCTURE_TYPE_HEADLESS_SURFACE_CREATE_INFO_EXT
#  undef VK_STRUCTURE_TYPE_MAX_ENUM
#  undef VK_TIMEOUT
#  undef VK_EVENT_SET
#  undef VK_EVENT_RESET
#  undef VK_INCOMPLETE
#  undef VK_ERROR_OUT_OF_HOST_MEMORY
#  undef VK_ERROR_OUT_OF_DEVICE_MEMORY
#  undef VK_ERROR_INITIALIZATION_FAILED
#  undef VK_ERROR_DEVICE_LOST
#  undef VK_ERROR_MEMORY_MAP_FAILED
#  undef VK_ERROR_LAYER_NOT_PRESENT
#  undef VK_ERROR_EXTENSION_NOT_PRESENT
#  undef VK_ERROR_FEATURE_NOT_PRESENT
#  undef VK_ERROR_INCOMPATIBLE_DRIVER
#  undef VK_ERROR_TOO_MANY_OBJECTS
#  undef VK_ERROR_FORMAT_NOT_SUPPORTED
#  undef VK_NOT_READY
#  undef VK_SUCCESS
#  undef VkPhysicalDevice
#  undef VkInstance
#  undef VkResult


